---
default:
  image: python:3.7
  before_script:
    - >-
        curl -sSL
        https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py
        | python -
    - source $HOME/.poetry/env
    - poetry config experimental.new-installer false
    - poetry config virtualenvs.in-project true
    - poetry install
  cache:
    key:
      files:
        - poetry.lock
      prefix: $CI_JOB_IMAGE
    paths:
      - .poetry
      - .venv
  tags:
    - docker

variables:
  POSTGRES_DB: test
  POSTGRES_USER: test
  POSTGRES_PASSWORD: ''

stages:
  - style
  - complexity
  - test
  - build

style:
  stage: style
  script:
    - poetry run black --check --diff {{ cookiecutter.project_slug }} tests

complexity:package:
  stage: complexity
  script:
    - poetry run radon cc {{ cookiecutter.project_slug }} -a -s
    - poetry run xenon -bB -mA -aA {{ cookiecutter.project_slug }}

complexity:tests:
  stage: complexity
  script:
    - poetry run radon cc tests -a -s
    - poetry run xenon -bB -mA -aA tests

.test:
  stage: test
  services:
    - postgres:11.2
    - selenium/standalone-chrome
  script:
    - export {{ cookiecutter.project_slug|upper }}_TEST_DB='postgresql://test@postgres/test'
    - export {{ cookiecutter.project_slug|upper }}_SELENIUM_HOST='selenium__standalone-chrome'
    - >-
        export {{ cookiecutter.project_slug|upper }}_LIVETEST_HOST=$(grep -Eio
        '^[0-9\.]*\s+runner-[0-9a-z_-]+-project-[0-9]+-concurrent-[0-9]+'
        /etc/hosts | awk '{ print $1; }')
    - >-
        poetry run pytest
        --junitxml=junit_report.xml
        --cov-report=xml:coverage.xml
  coverage: '/^TOTAL.+?(\d+(?:\.\d+)?\%)$/'
  artifacts:
    name: '$CI_PROJECT_NAME-coverage-$CI_COMMIT_SHORT_SHA-$CI_JOB_IMAGE'
    paths:
      - htmlcov
    reports:
      junit: junit_report.xml
      cobertura: coverage.xml

test:py36:
  extends: .test
  image: python:3.6

test:py37:
  extends: .test
  image: python:3.7

test:py38:
  extends: .test
  image: python:3.8

test:py39:
  extends: .test
  image: python:3.9

build:
  stage: build
  script:
    - poetry build
  dependencies: []
  artifacts:
    name: '$CI_PROJECT_NAME-build-$CI_COMMIT_SHORT_SHA'
    paths:
      - dist/
